# version: '3'

# services:
#   app1:
#     build:
#       context: .
#     # image: hello-k8s
#     environment:
#       - APP_NAME=hello-k8s-app1
#     ports:
#       - '3001:3000'

#   app2:
#     build:
#       context: .
#     # image: hello-k8s
#     environment:
#       - APP_NAME=hello-k8s-app2
#     ports:
#       - '3002:3000'

#   app3:
#     build:
#       context: .
#     # image: hello-k8s
#     environment:
#       - APP_NAME=hello-k8s-app3
#     ports:
#       - '3003:3000'

#   # nginx:
#   #   image: nginx:latest
#   #   container_name: reverse-proxy
#   #   ports:
#   #     - '80:80'
#   #   volumes:
#   #     - ./nginx.conf:/etc/nginx/nginx.conf:ro

version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=hello-k8s-app1
    ports:
      - '3001:3000'

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=hello-k8s-app2
    ports:
      - '3002:3000'

  app3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=hello-k8s-app3
    ports:
      - '3003:3000'

  nginx:
    image: nginx:latest
    container_name: reverse-proxy
    depends_on:
      - app1
      - app2
      - app3
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
